export const UPDATE_SLIDER = 'UPDATE_SLIDER';  
export const CHANNEL_DRAG_START = 'CHANNEL_DRAG_START';  
export const CHANNEL_DRAG_STOP = 'CHANNEL_DRAG_STOP';  
export const UPDATE_CATEGORY_SLIDER = 'UPDATE_CATEGORY_SLIDER';  

export const OUTCOMES_GET = 'OUTCOMES_GET';
export const OUTCOMES_UPDATE = 'OUTCOMES_UPDATE';

export const LANDINGPAGES_GET = 'LANDINGPAGES_GET';
export const LANDINGPAGES_UPDATE = 'LANDINGPAGES_UPDATE';
export const LANDINGPAGES_UPDATE_SLIDER = 'LANDINGPAGES_UPDATE_SLIDER';

export const DASHBOARD_GET = 'DASHBOARD_GET';

export const INTERNAL_SEARCH_TERM_ADD = 'INTERNAL_SEARCH_TERM_ADD';
export const INTERNAL_SEARCH_TERM_DELETE = 'INTERNAL_SEARCH_TERM_DELETE';
export const INTERNAL_SEARCH_TERM_UPDATE = 'INTERNAL_SEARCH_TERM_UPDATE';
export const EXTERNAL_SEARCH_TERM_ADD = 'EXTERNAL_SEARCH_TERM_ADD';
export const EXTERNAL_SEARCH_TERM_DELETE = 'EXTERNAL_SEARCH_TERM_DELETE';
export const EXTERNAL_SEARCH_TERM_UPDATE = 'EXTERNAL_SEARCH_TERM_UPDATE';
export const SEARCH_SLIDER_UPDATE = 'SEARCH_SLIDER_UPDATE';
export const SEARCH_SLIDER_DRAG_START = 'SEARCH_SLIDER_DRAG_START';
export const SEARCH_SLIDER_DRAG_STOP = 'SEARCH_SLIDER_DRAG_STOP';
 
export const REF_URLS_ADD = 'REF_URLS_ADD';
export const REF_URLS_DELETE = 'REF_URLS_DELETE';
export const REF_URLS_UPDATE = 'REF_URLS_UPDATE';

export const PROCESS_START = "PROCESS_START";
export const PROCESS_UPDATE = "PROCESS_UPDATE";
export const CAMPAIGNS_GET = 'CAMPAIGNS_GET';
export const CAMPAIGNS_TRAFFIC_UPDATE = 'CAMPAIGNS_TRAFFIC_UPDATE';
export const CAMPAIGNS_UPDATE = 'CAMPAIGNS_UPDATE';